/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Controladora;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.ModeloVendido;
import model.dao.ModeloVendidoDAO;

/**
 *
 * @author fonte
 */
public class DevVendaView extends javax.swing.JFrame {
    Controladora controller;
    //Dados para o front-end
    private String codVenda;
    private String cliente;
    private String data;
    
    public DevVendaView(){
        initComponents();
    }
    
    public DevVendaView(Controladora controladora, String codV, String nomeCliente, String dataVenda) {
        initComponents();
        this.codVenda = codV;
        this.cliente = nomeCliente;
        this.data = dataVenda;
        this.controller = controladora;
        preencheTabelaModelosVendidos();
        setDados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        tituloF = new javax.swing.JPanel();
        tituloL = new javax.swing.JLabel();
        corpo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbCliente = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbCod = new javax.swing.JLabel();
        lbData = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaItens = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbMotivo1 = new javax.swing.JCheckBox();
        cbMotivo2 = new javax.swing.JCheckBox();
        cbMotivo3 = new javax.swing.JCheckBox();
        cbMotivo4 = new javax.swing.JCheckBox();
        btnDevolver = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        container.setBackground(new java.awt.Color(153, 153, 153));

        tituloF.setBackground(new java.awt.Color(172, 88, 88));

        tituloL.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        tituloL.setForeground(new java.awt.Color(255, 255, 255));
        tituloL.setText("Devolução");

        javax.swing.GroupLayout tituloFLayout = new javax.swing.GroupLayout(tituloF);
        tituloF.setLayout(tituloFLayout);
        tituloFLayout.setHorizontalGroup(
            tituloFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloFLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(tituloL, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(498, Short.MAX_VALUE))
        );
        tituloFLayout.setVerticalGroup(
            tituloFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloL, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );

        corpo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Informações de venda");

        jLabel1.setText("Cliente:");

        lbCliente.setText("nomedocliente");

        jLabel2.setText("Data:");

        lbCod.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbCod.setText("Cod.0000000000");

        lbData.setText("00/00/0000");

        tabelaItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod. Modelo venda", "Marca", "Descrição", "Valor"
            }
        ));
        tabelaItens.setCellSelectionEnabled(true);
        jScrollPane2.setViewportView(tabelaItens);
        if (tabelaItens.getColumnModel().getColumnCount() > 0) {
            tabelaItens.getColumnModel().getColumn(0).setHeaderValue("Cod. Modelo venda");
            tabelaItens.getColumnModel().getColumn(1).setHeaderValue("Marca");
            tabelaItens.getColumnModel().getColumn(2).setHeaderValue("Descrição");
            tabelaItens.getColumnModel().getColumn(3).setHeaderValue("Valor");
        }

        jLabel3.setText("Itens da venda");

        jLabel4.setText("Motivo da devolução");

        cbMotivo1.setText("Motivo 1");

        cbMotivo2.setText("Motivo 2");

        cbMotivo3.setText("Motivo3");

        cbMotivo4.setText("Motivo 4");

        btnDevolver.setBackground(java.awt.SystemColor.controlHighlight);
        btnDevolver.setText("Solicitar devolução ↩");
        btnDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 151, 151));
        btnCancelar.setText("Cancelar ❌");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout corpoLayout = new javax.swing.GroupLayout(corpo);
        corpo.setLayout(corpoLayout);
        corpoLayout.setHorizontalGroup(
            corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(corpoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(corpoLayout.createSequentialGroup()
                        .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(corpoLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, corpoLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbData))
                            .addComponent(lbCod, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jScrollPane2)
                    .addGroup(corpoLayout.createSequentialGroup()
                        .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(corpoLayout.createSequentialGroup()
                                .addComponent(cbMotivo1)
                                .addGap(18, 18, 18)
                                .addComponent(cbMotivo2)
                                .addGap(18, 18, 18)
                                .addComponent(cbMotivo3)
                                .addGap(18, 18, 18)
                                .addComponent(cbMotivo4)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, corpoLayout.createSequentialGroup()
                        .addGap(0, 403, Short.MAX_VALUE)
                        .addComponent(btnDevolver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)))
                .addContainerGap())
        );
        corpoLayout.setVerticalGroup(
            corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(corpoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbCod, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(lbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(lbData, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(corpoLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMotivo1)
                            .addComponent(cbMotivo2)
                            .addComponent(cbMotivo3)
                            .addComponent(cbMotivo4))
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, corpoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDevolver)
                            .addComponent(btnCancelar))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(corpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addComponent(tituloF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(corpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverActionPerformed
        String estadoDevolucao;
        String motivo = "";
        int codModeloVendido = Integer.parseInt(tabelaItens.getValueAt(tabelaItens.getSelectedRow(), 0).toString());
        if(cbMotivo1.isSelected()){
            motivo+= "Motivo1";
        }
        if(cbMotivo2.isSelected()){
            motivo+= " ";
            motivo+= "Motivo2";
        }
        if(cbMotivo3.isSelected()){
            motivo+= " ";
            motivo+= "Motivo3";
        }
        if(cbMotivo4.isSelected()){
            motivo+= " ";
            motivo+= "Motivo4";
        }
        if(tabelaItens.getSelectedRow() != -1 && (motivo!="")){
            Object[] options = {"Sim", "Não"};
            int op = JOptionPane.showOptionDialog(null, "Solicitar devolução?", "Devolução", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
            estadoDevolucao = controller.realizarDevolucao(codModeloVendido, motivo);
            if(op == 0){
                if(estadoDevolucao.equals("Devolvido com sucesso!")){
                    JOptionPane.showMessageDialog(null, estadoDevolucao);
                }
                else{
                    JOptionPane.showMessageDialog(null, estadoDevolucao, "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Informe os dados corretamente!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDevolverActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        TabelaVendaView frame = new TabelaVendaView(this.controller);
        frame.setVisible(true);
        DevVendaView.this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DevVendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DevVendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DevVendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DevVendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new DevVendaView().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDevolver;
    private javax.swing.JCheckBox cbMotivo1;
    private javax.swing.JCheckBox cbMotivo2;
    private javax.swing.JCheckBox cbMotivo3;
    private javax.swing.JCheckBox cbMotivo4;
    private javax.swing.JPanel container;
    private javax.swing.JPanel corpo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbCliente;
    private javax.swing.JLabel lbCod;
    private javax.swing.JLabel lbData;
    private javax.swing.JTable tabelaItens;
    private javax.swing.JPanel tituloF;
    private javax.swing.JLabel tituloL;
    // End of variables declaration//GEN-END:variables
    
    //Customização do front-end
    public void setDados(){
        lbCod.setText("Cod.0000000"+codVenda);
        lbCliente.setText(cliente);
        lbData.setText(data);
    }
    
    public void preencheTabelaModelosVendidos(){
        DefaultTableModel modeloTb = (DefaultTableModel) tabelaItens.getModel();
        modeloTb.setNumRows(0);
        ModeloVendidoDAO mvdao = new ModeloVendidoDAO();
        
        for(ModeloVendido modeloVendido: controller.buscarModelosVendidos(Integer.parseInt(codVenda))){
            Object row[] = new Object[]{modeloVendido.getCod(), modeloVendido.getModelo().getMarca().getNome(), modeloVendido.getModelo().getDesc(), modeloVendido.getModelo().getPreco()};
            
            if(modeloVendido.getDevolvido()) row[3] = "[MODELO DEVOLVIDO]";
            
            modeloTb.addRow(row);
        }  
    }
}
