CREATE TABLE MAR_MARCA (
MAR_COD INT AUTO_INCREMENT PRIMARY KEY,
MAR_NOME VARCHAR(20) NOT NULL);

CREATE TABLE MTE_MODELO_TENIS (
MTE_COD INT AUTO_INCREMENT NOT NULL,
MTE_DESCRICAO VARCHAR(30) NOT NULL,
MTE_MARCA INT NOT NULL ,
MTE_PRECO FLOAT NOT NULL,
PRIMARY KEY (MTE_COD),
FOREIGN KEY (MTE_MARCA) REFERENCES MAR_MARCA(MAR_COD));

CREATE TABLE QES_QUANTIDADE_EM_ESTOQUE(
QES_MODELO_TENIS INT AUTO_INCREMENT NOT NULL,
QES_NUMERACAO INT NOT NULL,
QES_QUANTIDADE INT NOT NULL,
PRIMARY KEY (QES_MODELO_TENIS, QES_NUMERACAO),
FOREIGN KEY (QES_MODELO_TENIS) REFERENCES MTE_MODELO_TENIS(MTE_COD));

CREATE TABLE CLI_CLIENTE (
CLI_COD INT AUTO_INCREMENT NOT NULL,
CLI_NOME VARCHAR(50) NOT NULL,
CLI_CPF VARCHAR(14) NOT NULL,
CLI_LOGRADOURO VARCHAR(30),
CLI_NUMERO INT,
CLI_CIDADE VARCHAR(30),
CLI_ESTADO VARCHAR(2),
CLI_BAIRRO VARCHAR(20),
CLI_CEP VARCHAR(9),
CLI_EMAIL VARCHAR (30),
PRIMARY KEY (CLI_COD));

CREATE TABLE TCL_TELEFONES_CLIENTES(
TCL_NUMERO VARCHAR(18) NOT NULL,
TCL_CLIENTE INT NOT NULL,
TCL_COD INT AUTO_INCREMENT NOT NULL,
PRIMARY KEY(TCL_COD),
FOREIGN KEY(TCL_CLIENTE) REFERENCES CLI_CLIENTE(CLI_COD));

CREATE TABLE FUN_FUNCIONARIO (
FUN_COD INT AUTO_INCREMENT NOT NULL,
FUN_NOME VARCHAR(50) NOT NULL,
FUN_CPF VARCHAR(14) NOT NULL,
FUN_EMAIL VARCHAR(30) NOT NULL,
FUN_ADMINISTRADOR INT NOT NULL,
PRIMARY KEY (FUN_COD));

CREATE TABLE USU_USUARIO (
USU_NOME VARCHAR(15) NOT NULL,
USU_SENHA VARCHAR(15) NOT NULL,
USU_FUN INT,
PRIMARY KEY (USU_NOME),
FOREIGN KEY (USU_FUN) REFERENCES FUN_FUNCIONARIO(FUN_COD));

CREATE TABLE VEN_VENDA (
VEN_COD INT AUTO_INCREMENT NOT NULL,
VEN_CLIENTE INT NOT NULL,
VEN_FUNCIONARIO INT NOT NULL,
VEN_DATA_HORA DATETIME NOT NULL,
PRIMARY KEY (VEN_COD),
FOREIGN KEY (VEN_CLIENTE) REFERENCES CLI_CLIENTE(CLI_COD),
FOREIGN KEY (VEN_FUNCIONARIO) REFERENCES FUN_FUNCIONARIO(FUN_COD));